### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by cjl506** [DeniJsonC/WaveNet#1]
![image](https://github.com/DeniJsonC/WaveNet/assets/83258906/7919f837-0a87-4c1d-a489-7036f9ff139b)
测试的时候，提示这样的错误，该如何解决呢

**Comment by DeniJsonC** [comment]
> ![image](https://user-images.githubusercontent.com/83258906/280286763-7919f837-0a87-4c1d-a489-7036f9ff139b.png) 测试的时候，提示这样的错误，该如何解决呢

你好，我在测试时没有发现该问题，你可以尝试在主函数里用以下两句，而不调用‘load_checkpoint’函数运行一下：
checkpoint = torch.load($weights_path$, map_location=device)
model.load_state_dict(checkpoint)
