### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by Solitude1024** [DeniJsonC/WaveNet#11]
![image](https://github.com/DeniJsonC/WaveNet/assets/117899016/dbeb6137-9685-4e8a-be4d-b9cbc9be2e85)
![image](https://github.com/DeniJsonC/WaveNet/assets/117899016/d35eb4f5-5743-46a1-a8c5-7404ad3e4432)
作者你好，请问这个报错是cuda哪里用错了吗？

**Comment by DeniJsonC** [comment]
> ![image](https://private-user-images.githubusercontent.com/117899016/332402150-dbeb6137-9685-4e8a-be4d-b9cbc9be2e85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDE4NzQsIm5iZiI6MTcxNjM0MTU3NCwicGF0aCI6Ii8xMTc4OTkwMTYvMzMyNDAyMTUwLWRiZWI2MTM3LTk2ODUtNGU4YS1iZTRkLWI5Y2JjOWJlMmU4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwMTMyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTc5NjFmZDE1YTkwYTA0NzA5ODhlZTNhZWZiYTBkM2ZlNTRkOTY0NDA2MTMzYTEwMTZlNzBiYzEzMTE0NTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-WV9G-ND_6piqxnY8oAGPmdPhnTA_E178aesGK0o1HY) ![image](https://private-user-images.githubusercontent.com/117899016/332402399-d35eb4f5-5743-46a1-a8c5-7404ad3e4432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDE4NzQsIm5iZiI6MTcxNjM0MTU3NCwicGF0aCI6Ii8xMTc4OTkwMTYvMzMyNDAyMzk5LWQzNWViNGY1LTU3NDMtNDZhMS1hOGM1LTc0MDRhZDNlNDQzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwMTMyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjQ1ZDVlNTkxMDlhNDA0NDJkOTFiMzA4MTQyY2NmZWI4OTJjNmNjMmZiZDk4NDZkNTc3ZGVjYjJhNmRhOTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UZmxe6NjBlsKp-2hGjt1hAjwNvAU9w0jETXUlQdVi7I) 作者你好，请问这个报错是cuda哪里用错了吗？

你好，从报错来看是你模型加载的权重是放在gpu上的，而输入的图像数据是放在cpu上的。将
retored = model(restored)(用于cpu测试)改为restored=model(restored.cuda())（用于gpu测试）即可。我刚刚更新了demo.py文件，感谢你的反馈
