### ISSUE TITLE
> 作者你好，我有一些关于训练的问题，对于训练命令“./train.sh Enhancement/Options/WaveNet____.yml”：

### ISSUE THREAD

**Issue by Solitude1024** [DeniJsonC/WaveNet#13]
> 作者你好，我有一些关于训练的问题，对于训练命令“./train.sh Enhancement/Options/WaveNet____.yml”：
> 
> （1）是不是从零开始的训练？即 是否加载预训练权重 （前提：我想稍微魔改一下网络试试）对于“**修改网络后加载预训练权重训练**”，根据我查到的方法，是将**net.load_state_dict()**中的strict设置为False，但是.load_state_dict()似乎只在demo.py中存在，train.py中没有找到。 （2）与（1）相关的是，以Enhancement/Options/WaveNet_B_LOL.yml为例，62-66行 #path中三个参数的含义我不太确定，如何设置呢？

A(1)：你好，要fine tune的话 你可以直接在/basicsr/train.py文件166-188行修改为具体的预训练权重路径就行了。
A(2)：具体参数以及更深层的定制化可以参考basicSR官方文档，[https://github.com/XPixelGroup/BasicSR-docs](url)

_Originally posted by @DeniJsonC in https://github.com/DeniJsonC/WaveNet/issues/12#issuecomment-2132793833_

**Comment by Solitude1024** [comment]
感谢你的细心回答，还有两个小问题：
（1）训练命令“./train.sh Enhancement/Options/WaveNet____.yml”是从头开始训练吗？
（2）最终的权重保存路径

**Comment by DeniJsonC** [comment]
> 感谢你的细心回答，还有两个小问题： （1）训练命令“./train.sh Enhancement/Options/WaveNet____.yml”是从头开始训练吗？ （2）最终的权重保存路径

A(1)：是的，从第一轮迭代开始训练。
A(2)：最终权重会保留训练时自动生成的experiments/XXX(yml配置文件中“name”关键字)/文件夹下。

**Comment by Solitude1024** [comment]
明白了！
&nbsp;


鉁惜&amp;#x10E6;壅有
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月27日(星期一) 下午3:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DeniJsonC/WaveNet] &gt; 作者你好，我有一些关于训练的问题，对于训练命令“./train.sh Enhancement/Options/WaveNet____.yml”： (Issue #13)














  
感谢你的细心回答，还有两个小问题： （1）训练命令“./train.sh Enhancement/Options/WaveNet____.yml”是从头开始训练吗？ （2）最终的权重保存路径
  
A(1)：是的，从第一轮迭代开始训练。
 A(2)：最终权重会保留训练时自动生成的experiments/XXX(yml配置文件中“name”关键字)/文件夹下。
