### ISSUE TITLE
训练报错及断点续训

### ISSUE THREAD

**Issue by Solitude1024** [DeniJsonC/WaveNet#14]
作者你好，我最近几天对WaveNet进行训练，出现了一些问题，未能解决，特来请教
1.训练报错
![423941dd908d0397dc48229a6539b2b9](https://github.com/DeniJsonC/WaveNet/assets/117899016/44ae001b-e2d7-4faf-b8aa-7533b92996d3)
![053f010961adb3383aefaf344ba5cd29](https://github.com/DeniJsonC/WaveNet/assets/117899016/90826610-b7ee-474d-8c10-3f19a45e7ccb)
在两次训练中均出现此问题（都在第979个epoch）
2.在出现问题1后，尝试了手动和自动断点续训两种方法
![45e171db6cdc6c13540da8395924b8ba](https://github.com/DeniJsonC/WaveNet/assets/117899016/b24c924e-f3b8-46b8-bad8-c3f3df2ee7de)
是文件名引起的bug吗？

**Comment by DeniJsonC** [comment]
> 作者你好，我最近几天对WaveNet进行训练，出现了一些问题，未能解决，特来请教 1.训练报错 ![423941dd908d0397dc48229a6539b2b9](https://private-user-images.githubusercontent.com/117899016/335909786-44ae001b-e2d7-4faf-b8aa-7533b92996d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODE2MzYsIm5iZiI6MTcxNzM4MTMzNiwicGF0aCI6Ii8xMTc4OTkwMTYvMzM1OTA5Nzg2LTQ0YWUwMDFiLWUyZDctNGZhZi1iOGFhLTc1MzNiOTI5OTZkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwMjIyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDBhNjU0YmUzOTYzMWIyZjVjZTQ5OTgxMGJmOWMwY2NiNDNmZTI2Mjg2MWU5MWRmY2M3MmZmNjJjYzZjMDkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sbpKB1JUTtYr-DELxx1j8MK-9bN9mjusMEcYDB_ufbM) ![053f010961adb3383aefaf344ba5cd29](https://private-user-images.githubusercontent.com/117899016/335909827-90826610-b7ee-474d-8c10-3f19a45e7ccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODE2MzYsIm5iZiI6MTcxNzM4MTMzNiwicGF0aCI6Ii8xMTc4OTkwMTYvMzM1OTA5ODI3LTkwODI2NjEwLWI3ZWUtNDc0ZC04YzEwLTNmMTlhNDVlN2NjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwMjIyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjE2MmViMjYzM2RhOGEwMWJjODA4ZGUwMTJkZmNlYjNlZjAzMjA4NDc5NDY0YzJkMGIzZTYxMjk1MzBhMTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pt7ztFt8sWO8X8OrkqelyfoMtPpnrTwU5w-k6_NsF2k) 在两次训练中均出现此问题（都在第979个epoch） 2.在出现问题1后，尝试了手动和自动断点续训两种方法 ![45e171db6cdc6c13540da8395924b8ba](https://private-user-images.githubusercontent.com/117899016/335910024-b24c924e-f3b8-46b8-bad8-c3f3df2ee7de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODE2MzYsIm5iZiI6MTcxNzM4MTMzNiwicGF0aCI6Ii8xMTc4OTkwMTYvMzM1OTEwMDI0LWIyNGM5MjRlLWYzYjgtNDZiOC1iYWQ4LWMzZjNkZjJlZTdkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwMjIyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzUyMTNiMTJhOGNiNjM5MTRkMzIzNmY3YjRlYTAxODg4OThiNDcxZjUxNDJlZjgwOTBkYmUyNGY3NmI1ZGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fxaFFLy0mHDK-UwJuUtg1JAUgo_HhOtl-6PISxC1Tb8) 是文件名引起的bug吗？

你好，A1:建议你检查训练的epoch 和学习率，还有scheduler的设置是否正确
A2:配置文件resume_state这项设置成"resume_state:~"，如果你要手动加载指定state，可以在train.py 178行手动指定“max_state_file='xxx.state'”，报错是因为 train.py默认是加载最新的"迭代次数.state"文件，所以是int类型，如:'5000.state'。

**Comment by Solitude1024** [comment]
好的，感谢
&nbsp;


鉁惜&amp;#x10E6;壅有
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月3日(星期一) 上午10:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DeniJsonC/WaveNet] 训练报错及断点续训 (Issue #14)














  
作者你好，我最近几天对WaveNet进行训练，出现了一些问题，未能解决，特来请教 1.训练报错   在两次训练中均出现此问题（都在第979个epoch） 2.在出现问题1后，尝试了手动和自动断点续训两种方法  是文件名引起的bug吗？
  
你好，A1:建议你检查训练的epoch 和学习率，还有scheduler的设置是否正确
 A2:配置文件resume_state这项设置成"resume_state:~"，如果你要手动加载指定state，可以在train.py 178行手动指定“max_state_file='xxx.state'”，报错是因为 train.py默认是加载最新的"迭代次数.state"文件，所以是int类型，如:'5000.state'。
