### ISSUE TITLE
测试图片指标问题

### ISSUE THREAD

**Issue by xuehaohewangyu** [DeniJsonC/WaveNet#16]
我运行evaluate.py出现
![image](https://github.com/DeniJsonC/WaveNet/assets/118803631/ce0a0462-dccc-4ed6-97ec-d36dff582dd2)
如何解决

**Comment by DeniJsonC** [comment]
> 我运行evaluate.py出现 ![image](https://private-user-images.githubusercontent.com/118803631/343753987-ce0a0462-dccc-4ed6-97ec-d36dff582dd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTA5OTgsIm5iZiI6MTcxOTQ5MDY5OCwicGF0aCI6Ii8xMTg4MDM2MzEvMzQzNzUzOTg3LWNlMGEwNDYyLWRjY2MtNGVkNi05N2VjLWQzNmRmZjU4MmRkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMjE4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWZlNGM3ZmY1ZTM2NWU5M2I4Y2M1ZjYzZWFmNDJhMWViMzBiYjkyZGU0MjIxNzY1YzRjOTUxMTQzNzQ0OTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OFxqYeb4UZQvoGzLaVgZQm_S-ZqdkD6jVnSKx4MAiH8) 如何解决

你好，你需要把evaluate.py 118行 use_gpu 设置成False

**Comment by xuehaohewangyu** [comment]
命令该怎么写？
python evaluation.py -dirA D:\llfw--reproduce\pinyu\WaveNet-main-2023/visual\loltest/ -dirB D:\llfw--reproduce\pinyu\WaveNet-main-2023\lolv1/lolhigh/ -type png --use_gpu False？

**Comment by xuehaohewangyu** [comment]
作者能答复一下吗？
