### ISSUE TITLE
train代码开源了吗？

### ISSUE THREAD

**Issue by zhangshengpeng2021** [DeniJsonC/WaveNet#2]
train代码开源了吗？

**Comment by DeniJsonC** [comment]
> train代码开源了吗？
你好 已经开源了，欢迎反馈问题。

**Comment by zhangshengpeng2021** [comment]
![屏幕截图 2023-11-10 141600](https://github.com/DeniJsonC/WaveNet/assets/87418524/ee5790b0-e29c-483a-a63f-7d9b525dfff8)
你好，运行demo.py文件提示这个错误，提示缺少models，但是没有找见所属的库，请问需要导入那个库还是需要相应的py文件？

**Comment by DeniJsonC** [comment]
> ![屏幕截图 2023-11-10 141600](https://user-images.githubusercontent.com/87418524/281975053-ee5790b0-e29c-483a-a63f-7d9b525dfff8.png) 你好，运行demo.py文件提示这个错误，提示缺少models，但是没有找见所属的库，请问需要导入那个库还是需要相应的py文件？
好了，你需要把demo.py 还有evaluation.py 移动到basicsr目录下，然后 uninstall basicsr 再重新 python setup.py develop --no_cuda_ext

**Comment by zhangshengpeng2021** [comment]
![屏幕截图 2023-11-10 160548](https://github.com/DeniJsonC/WaveNet/assets/87418524/2ee50ec1-a53a-4ae3-a2f0-b47394e9a023)
不好意思，用的是作者提供的数据集和权重，存在输入和输入不匹配的错误，请问什么原因？

**Comment by zhangshengpeng2021** [comment]
> ![屏幕截图 2023-11-10 160548](https://user-images.githubusercontent.com/87418524/281996919-2ee50ec1-a53a-4ae3-a2f0-b47394e9a023.png) 不好意思，用的是作者提供的数据集和权重，存在输入和输入不匹配的错误，请问什么原因？

cpu可以，gpu就会出错。

**Comment by Albertchamberlain** [comment]
![image](https://github.com/DeniJsonC/WaveNet/assets/47343901/5ba8cf8d-b245-412f-bc8b-f481f447d97f)
你好运行以下命令报错，python demo.py --input_dir /home/cicero/hbx/whl/WaveNet/datasets/LOL/eval15/low  --result_dir /home/cicero/hbx/whl/WaveNet/SAVE_dir   --weights /home/cicero/hbx/whl/WaveNet/checkpoints/LOL/WaveNet_T_LOL.pth

**Comment by Albertchamberlain** [comment]
OK，Hello，我想我发现了问题所在，作者把模型checkpoint弄反了，SID的是LOL的数据集checkpoint模型

**Comment by DeniJsonC** [comment]
> OK，Hello，我想我发现了问题所在，作者把模型checkpoint弄反了，SID的是LOL的数据集checkpoint模型

hello, 这是在训练的时候额外保存其他数据，单独设置了['state_dict']项来存储weight，现在已经把所有模型统一成了无需加载具体的['state_dict'], 具体参考新上传的demo.py文件。
