### ISSUE TITLE
LOL测试问题

### ISSUE THREAD

**Issue by Xingshi-tech** [DeniJsonC/WaveNet#3]
您好，我在使用LOL文件夹下的权重进行demo.py测试的时候出现了以下问题
![image](https://github.com/DeniJsonC/WaveNet/assets/72507096/22ee7def-fa75-4e52-b6d3-a1016f230eeb)
![image](https://github.com/DeniJsonC/WaveNet/assets/72507096/3963847d-1c83-44bf-b878-c5b747e3c5c7)

**Comment by ycwsilent** [comment]
请问一下，您是怎么解决的呢
我现在运行LOL文件夹下权重没有问题，在5k权重上出现和你一样的错误
