### ISSUE TITLE
Mixup data augmentation

### ISSUE THREAD

**Issue by Arusa1** [DeniJsonC/WaveNet#4]
Hi, thank for your amazing work. 
You mentioned in the paper that mixup is adopted for data augmentation. Could you please tell me exactly where the code implements this in this repository?  Thanks!

**Comment by DeniJsonC** [comment]
> Hi, thank for your amazing work. You mentioned in the paper that mixup is adopted for data augmentation. Could you please tell me exactly where the code implements this in this repository? Thanks!
Hi, Arusa1. The MixUp codes you can find in the path "basicsr/models/image_restoration_model.py" line #22

**Comment by DeniJsonC** [comment]
> Hi, thank for your amazing work. You mentioned in the paper that mixup is adopted for data augmentation. Could you please tell me exactly where the code implements this in this repository? Thanks!

Hi, Arusa1. The MixUp codes you can find in the path "basicsr/models/image_restoration_model.py" line #22

**Comment by Arusa1** [comment]
Thanks! :)
